### ISSUE TITLE
Game Path

### ISSUE THREAD

**Issue by Trozmagon** [AB1908/GOG-Galaxy-Export-Script#31]
Hi, first off thanks for your work on this script, I'm wondering if it's at all possible to include the launch path? e.g: executable path + launch arguments?

I am a developer but I'm not familure with python so if you can confirm if this is possible then I'm happy to do the leg work, I'd just rather know before I start learning to find out it's not.

Thanks.

**Comment by Varstahl** [comment]
I'm not entirely sure what you mean by that, what executable? If you mean "I open a shell somewhere and want to to run the file" you can invoke `\path\of\python.exe "\path\of\galaxy_library_export.py" <parameters>`, or if you want to just run it from explorer you can just create a small batch script like so and put it in the same path as the `galaxy_library_export.py`:

```batch
@echo off
pushd %~dp0
python galaxy_library_export.py <parameters>
popd
```

If `python.exe` is not on the path, you may also specify a direct path to the executable, like:

```batch
@echo off
pushd %~dp0
C:\Program Files\Python\python.exe galaxy_library_export.py <parameters>
popd
```

If I misunderstood your question, feel free to clarify.

**Comment by Trozmagon** [comment]
Sorry, you're right I wasn't very clear, I mean the executable path of the game in a new column within the csv.

So let's say you have the Cemu intergration installed, and you have Breath of the Wild as a launchable game within GOG Galaxy, I would like to output in the CSV the full exe path + arguments, ""C:\Cemu\Cemu.exe" -f -g "C:\Cemu\Games\The Legend of Zelda Breath of the Wild\code\U-King.rpx"".

Does that clear it up?

**Comment by Varstahl** [comment]
ah, yes, got it now. That's quite problematic actually, I don't think that's possible.

Example: steam games are opened through URLs `steam://launch/<numeric_id>`, you don't launch executables. We might export IDs to extrapolate for some, but it's going to be platform dependant.

Also, you might have the same game on multiple platforms and only one of them installed, that also would require some more per-platform parsing.

Some of it is possible, but it's not a matter of exporting data, it's a matter of parsing all the installed plugins manually and figuring out how it works. I'm not sure if it's worth working on it in this plugin, since this just exports game data from galaxy's local database.

**Comment by Trozmagon** [comment]
Ahhh damn, that's not what I wanted to hear :( I was hoping it would be available in the gog data model. Thanks anyway mate.

**Comment by Varstahl** [comment]
If you have something specific it can be worked out, but no, it isn't.
