### ISSUE TITLE
Request / Question: Import & Tags

### ISSUE THREAD

**Issue by Countryen** [AB1908/GOG-Galaxy-Export-Script#4]
2 Requests / Questions:
- Export Tags?
- Import?

# 1. Export Tags
Can the script export tags or will you include tags in the near future?
Also other details like images, alternative titles, set installed locations / exe paths etc.?

# 2. Import
Do you know if it's possible/"ok" to import the exported data back into the client?
Did you test it / do you have information about it?
Do you consider making an importer?

**Comment by AB1908** [comment]
1. I think tags can be exported but I'll have to test this idea first. I don't recall seeing tags in any of their databases. Images, alternative titles and the like were there in the database. As for installed locations, I think that's in another database as well. Maybe use the SQL commands listed in the wiki if you're interested in looking around?

2. I think it's a bad idea to import data back into the client. It'll likely get overwritten anyway because their databases appear to constantly be refreshed. You technically _can_ do it though. It'll just involve a bunch of SQL queries. I'd help if you wanted to make one but I certainly won't make one myself.

**Comment by Countryen** [comment]
Thanks for the reply/information. I'll post here if I manage to do it / have a working exporter for tags / importer, if they are needed. Thanks for the detailed wiki, too.
